ga4gh/vrs

schema/vr.json, schema/vr.yaml, tests/functions.yaml, tests/models.yaml, tests/utils.yaml
closes #55
* Also made a few typo corrections and cleanup
=> pared down schema and corresponding tests

docs/source/terms_and_model/terms_and_model.rst
Thanks @pnrobinson! Let me know if this addresses your suggested change.
=> closes #65

schema/vr.json, schema/vr.yaml
This PR implements my recent proposal in #56, which is a slight variation on Alex's proposal.
(It's also basically where VMC was several months ago. :-()
Ideally, we'd have more discussion, but we're under a deadline. So, pressing on.
=> Closes #56: clarify id and identifier

docs/source/specification/terms_and_model/variation.rst
@reece will need a quick look-over here.
=> describe Text subclass of Variation

docs/source/implementations/reference_implementation.rst
Change to format of Variation subclasses
=> Typos and format change

docs/source/specification/terms_and_model/index.rst
=> Remove or change persist recommendation

docs/source/specification/computed_identifiers/normalization.rst
Update author name in reference to SPDI Data Model to be `LAST NAME, FI. MI.`
=> Fix typo in reference

docs/source/appendices/future_plans.rst, docs/source/appendices/vr-python/Overview.rst, docs/source/impl-guide/computed_identifier.rst, docs/source/impl-guide/normalization.rst, docs/source/impl-guide/required_data.rst, docs/source/implementations.rst
Small change as VR-Spec used in other places in spec.
=> Replace 'VR Spec' with VR-Spec

docs/source/appendices/development_process.rst, docs/source/appendices/future_plans.rst, docs/source/appendices/ga4gh_identifiers.rst, docs/source/impl-guide/computed_identifiers.rst, docs/source/impl-guide/index.rst, docs/source/impl-guide/required_data.rst, docs/source/implementations.rst, docs/source/schema.rst, docs/source/terms_and_model.rst
=> Capitalization issue 77

docs/source/appendices/implementations.rst, docs/source/impl-guide/computed_identifiers.rst, docs/source/terms_and_model.rst
=> #160: provide brief _id slot alternate id example in note.

docs/source/impl-guide/examples/hgvs-translation.rst
=> WIP: add walk-through

docs/source/appendices/truncated_digest_collision_analysis.rst
Addresses issue #182 
Reece: Please re-generate the table at the bottom of the page using the patched code.  This patch will change the numbers significantly.
=> Patch collision probability code in appendix

docs/source/impl-guide/normalization.rst
Citing the peer-reviewed version rather than the preprint.
=> Update citation of SPDI Paper

docs/source/terms_and_model.rst
Revisions to the recently merged #203
=> 181 chromosomelocation

CONTRIBUTORS.md
Trivial PR adding myself to the contributors list.
=> Updated contributors

docs/source/appendices/implementations.rst
Updating the paragraph on BRCA Exchange's implementation of VRS
=> Update the BRCA Exchange paragraph

docs/source/terms_and_model.rst
Updating quoting to be same as other examples
=> Update quoting in CytobandInterval examples

README.md, docs/source/appendices/design_decisions.rst, docs/source/releases.rst, docs/source/terms_and_model.rst
Bah. Accidentally branched from `master`, pulling in the README changes for this v1.1 patch. I see no reason to exclude it though, so leaving.
=> patch 1.1.1 (b)

docs/source/impl-guide/computed_identifiers.rst, docs/source/releases.rst, docs/source/terms_and_model.rst, schema/vr.json, schema/vr.yaml
* Add computed ID prefix for ChromosomeLocations
=> Patch 1.1.2 - Update ChromosomeLocation Prefix

docs/source/terms_and_model.rst
Simple change, but you've been closer to this. Please approve/improve.
=> #240: update cytoband ordering

CONTRIBUTING.md
=> #250: Add CONTRIBUTING.md

CONTRIBUTORS.md, docs/source/appendices/development_process.rst
=> #252: Update contributors and leadership

docs/source/appendices/future_plans.rst, docs/source/conf.py, docs/source/impl-guide/computed_identifiers.rst, docs/source/impl-guide/example.rst, docs/source/schema.rst, docs/source/terms_and_model.rst, schema/vrs.json, schema/vrs.yaml
@ahwagner @larrybabb : In order to review the changes that Alex has made in the last few days, I created a branch retroactively for them, reset develop back to the merge, and created this PR.
**Important:** This required a force push. You will need to pull develop again.
=> Alex's Complete Changes

schema/vrs.json, schema/vrs.yaml, schema/y2j
=> #282: VariationSet in VRS Python

schema/vrs.json, schema/vrs.yaml
PR to address punch-list in #285.
Currently handles changes to Numeric. A few additional changes coming prior to advancing to full PR.
=> RFC: #285 Use generalized ranges for locations and counts

schema/helpers.py, schema/vrs.json, schema/vrs.yaml
=> #301 add constraints

docs/source/terms_and_model.rst
... also be less prescriptive above upgrade mechanisms at this time.
=> Closes #319: Dissuade users from Text variation unless necessary

schema/vrs-source.yaml, schema/vrs.json, schema/vrs.yaml
=> replaces single-value enum with const for types

schema/defs/vrs/CytobandInterval.rst, schema/vrs-source.yaml, schema/vrs.json, schema/vrs.yaml
=> Revise Cytoband Interval definition

schema/defs/vrs/Number.rst, schema/vrs-source.yaml, schema/vrs.json, schema/vrs.yaml
=> update Number class to be integer values only

schema/defs/vrs/CopyNumber.rst, schema/vrs-source.yaml, schema/vrs.json, schema/vrs.yaml
=> revise copynumber definition

.requirements.txt, schema/defs/vrs/CytobandInterval.rst, schema/defs/vrs/Haplotype.rst, schema/vrs-source.yaml, schema/vrs.json, schema/vrs.yaml
- update python-jsonschema-objects version to >=0.4.0
- fix typo in CytobandInterval end
- Regenerate vrs yaml/json to update members to have 2 min items
=> fix: get smoketests to pass

validation/models.yaml
Close #405
- Absolute / Relative Copy Number now have a CURIE as the subject
- Add test models for GenotypeMember + Genotype
=> Update validation models
