ga4gh/vrs

docs/source/index.rst
docs/source/specification/terms_and_model/index.rst
docs/source/specification/terms_and_model/interval.rst
schema/vr.json
schema/vr.yaml

Some typos fixed, and added use of RFC 2119 in a couple of places. The link to the `Interbase Interval Tests` is now fixed, but it points to an archived file; it should be decided whether to keep it.
In addition to these small changes, I have some suggestions or questions from the [terms and model index page](https://vr-spec.readthedocs.io/en/latest/specification/terms_and_model/index.html):
* Receiving systems SHOULD NOT persist Ids from remote sources. Instead, Identifiers (below) SHOULD be used for communication between systems. -> MUST (NOT) instead of SHOULD (NOT)?
* Use of 'MUST' instead of 'SHALL' could remove the ambiguity that word has (can be a suggestion or a command)

Fixed some typos, use of RFC 2119 and links

---

docs/source/appendices/design_decisions.rst
docs/source/specification/computed_identifiers/normalization.rst
docs/source/specification/terms_and_model/interval.rst
docs/source/specification/terms_and_model/location.rst

Grammar fixes and headings

---

schema/vr.json
schema/vr.yaml
validation/models.yaml

This minor change allows a Allele.location property to be an object (as-is) or a CURIE (new). See #173 for elaboration.
vr-python has minor updates to facilitate this change, which I'll commit separately.

#173: Allow Allele.location to be a CURIE

---

docs/source/terms_and_model.rst

The computational definition of `State` should be more concrete, and I propose we remove some of the planned concepts that ultimately may or may not become `State` classes (which, per our definition of `State`, makes them allowable under `Allele`).

Remove examples of planned states from State definition

---

docs/source/terms_and_model.rst

Currently the computational definition of `Allele` is (emphasis added):
>An Allele is a **specific**, single, and contiguous Sequence at a Location (Abstract Class). Each alternative Sequence may be empty, shorter, longer, or the same length as the interval (e.g., due to one or more indels).
I propose removing "**specific**", due to the nature of Allele in allowing any `State` and `Location` object and the (ironic) ambiguity of how "specific" is meant to constrain those types (e.g. IUPAC ambiguity codes used in `SequenceState.sequence`), if at all.

remove "specific" qualifier per concerns in #109

---

schema/vr.json
schema/vr.yaml

We have decided to wait on the use of `Location` in `Haplotype` until consensus is reached on implementation details. This is a forward-compatible decision that will unblock other efforts.
While our documentation was updated to reflect this change, the schema itself was not. This PR makes the corresponding change to the schema.

Remove Haplotype Location

---

docs/source/appendices/design_decisions.rst
docs/source/impl-guide/computed_identifiers.rst
docs/source/impl-guide/normalization.rst

This PR addresses shortcomings of the current description of normalization. As stated in [this comment on #193](https://github.com/ga4gh/vr-spec/issues/193#issuecomment-660556914), the goals of this PR are:
* Reserve the word "normalization" to mean the canonicalization process for all Variation classes.
* Require normalization prior to creating a computed identifier for all Variation classes.
* Modify current Allele normalization to handle ref agree, as follows:
* In §2. Condition, add "If the reference and alternate alleles are empty, return the input location and alleles."
The majority of the changes are rendered in https://vr-spec.readthedocs.io/en/193-ref-allele-normalization/impl-guide/normalization.html. 
https://vr-spec.readthedocs.io/en/193-ref-allele-normalization/impl-guide/comp …

#193: ref allele normalization

---

README.md
docs/source/appendices/associating-annotations.rst
docs/source/appendices/design_decisions.rst
docs/source/appendices/implementations.rst
docs/source/impl-guide/example.rst
schema/ga4gh.yaml
schema/vr.yaml

Main change for 1.1rc is typo on annotation.
Minor changes VR to VRS, json schema to JSON schema, may not be needed.
Pull request on 1.1rc not sure if should be this branch or master?

Doc updates 1.1rc

---

docs/source/releases.rst
docs/source/terms_and_model.rst

Changes:
- fix typo in Allele information model
Additional changes for the 1.1.1 patch should be added to the `1.1.1-patch` branch prior to merging this PR.

Patch version 1.1.1

---

docs/source/appendices/design_decisions.rst
docs/source/impl-guide/example.rst
docs/source/style.rst
docs/source/terms_and_model.rst
notebooks/develop.ipynb
notebooks/nbsupport
schema/vrs.json
schema/vrs.yaml

See rendering in https://vrs.ga4gh.org/en/46-repeat-and-abundance/terms_and_model.html.
Changes in other files are insignificant.
Changes:
* Added documentation for LiteralSequence, DerivedSequence, RepeatedSequence, SequenceExpressions
* Added documentation for both Abundance classes
* Renamed Range to IntegerRange. (Seems that we might want a float range later.)
* Deprecated State and SequenceState
* Rearranged variation to use Molecular, Systemic, Other taxonomy
* Rearranged for top-down presentation (i.e., variation → location → sequence expressions → primitive, rather than the inverse order)
Note: I do *not* think this documentation is perfect. However, I do think that this PR substantially addresses the needs of this issue. We can then come back for more polishing.

46 repeat and abundance

---

.github/workflows/stale.yml

Currently "stayin alive" labeled issues are labeled stale and removed. This PR fixes that.

Keep issues alive

---

schema/vrs.json
schema/vrs.yaml

Schema now validates against use of sequence expression, provided it is not repeated sequence expression.
Example of repeated literalsequence (validates): https://www.jsonschemavalidator.net/s/BU5tKVum
Example of repeated repeatedsequence (does not validate): https://www.jsonschemavalidator.net/s/n5BIklGI
Closes #287.

closes #287

---

.github/workflows/tests.yml
schema/helpers.py
schema/vrs.json
schema/vrs.yaml
tests/config.py
tests/test_basic.py

Two recent changes conflict with python-jsonschema-objects, an essential library used by vrs-python.
I attempted several workarounds but eventually had to drop the conditional required. 
Again, no workarounds were found. Apparently, PJS can't support the recursion created by the negated constraint even though it can handle simpler recursion through a parent class.

Fixes #295: Revert schema changes that cause exceptions in pjs

---

notebooks/Examples and Validation Tests.ipynb
schema/y2j
validation/models.yaml

This branch contains validation tests for all non-abstract classes in VRS.
VRS python HEAD (as of d806dd4, but not earlier) executes these tests as-is.
Tests are framed around VRS classes. In this PR, each class has exactly one test, but having other tests is possible.
For each test, there is an output block that defines the expected output for zero or more functions.
So, for
```
Number:
-
in:
type: Number
value: 55
out:
ga4gh_serialize: '{"type":"Number","value":55}'
```
Interpret as: This test is for the class `Number`. There is one test (`-` is the start of an array). The `in` block defines the class attributes to create an instance. That instance is passed to `ga4gh_serialize`, which is expected to return the given string.

258 update validation tests

---

docs/source/appendices/development_process.rst

The develop branch for community review is an outdated process that we no longer follow. Recommend removing since the develop branch no longer exists.

remove reference to develop branch

---

docs/source/terms_and_model.rst
schema/defs/vrs/ComposedSequenceExpression.rst
schema/vrs-source.yaml
schema/vrs.json
schema/vrs.yaml

add ComposedSequenceExpressions

---

schema/defs/vrs/ComposedSequenceExpression.rst
schema/vrs-source.yaml
schema/vrs.json
schema/vrs.yaml

The Allele's `state` property can either be a SequenceExpression or a SequenceState. The latter is deprecated, but was listed first, which means some implementing tools attempt to use it before trying SequenceExpressions (which causes some problems). Swapping the order solves the more immediate problem.

Fix Allele state type priority

---

README.md
schema/vrs-source.yaml
schema/vrs.json
schema/vrs.yaml

Ran tests in vrs-python (removed where we explicitly set `type` in the models) and everything passes

Add default value for types + update readme for using smoketests

---

schema/vrs.yaml

The description for `end` used `start` ... No code change.

C & P error fix in CytobandInterval

---

validation/models.yaml

Updating `models.yaml` to take into account the `ordered` property in array fields. 
The docs will be updated with this new rule in #410

fix: models.yaml to take ordered property in account

---

tests/test_basic.py
validation/models.yaml

Close #406
Before, we would find out that the examples in models.yaml were invalid through vrs-python tests. This added test will allow us to know in this repo

Add tests to check schema validation in models.yaml (#406)

---

validation/models.yaml

Add tests for ComposedSequenceExpression (#408)

---

docs/source/terms_and_model.rst
schema/defs/vrs/CopyNumberChange.rst
schema/vrs-source.yaml
schema/vrs.json
schema/vrs.yaml
validation/models.yaml

IMO `relative_copy_class`  should be `copy_assessment` in the `CopyNumberChange` example?

relative_copy_class  -> copy_assessment in `CopyNumberChange` example

---

schema/vrs-source.yaml

Initial work for #432 
@ahwagner I'm unable to run the `make all` commands due to errors. But wanted to update the case since it will affect digests

fix: use camel case for copy change

---

schema/vrs-source.yaml
schema/vrs.yaml
validation/models.yaml

Close #440 
- Updated models.yaml with the name change

feat!: SequenceLocation.sequence --> SequenceLocation.sequenceReference

---

validation/models.yaml

Main changes:
- `SequenceReference` digest is `referenceSequence.refgetAccession.split("SQ.")[-1]`
- Copy Number `subject` renamed to `location`
Questions:
- I'm not sure about `SequenceReference`. I currently have it so that `ga4gh_identify` and `ga4gh_serialize` return null. It's under the IDENTIFABLE TYPES sections, so it should return a response for `ga4gh_identify`. Would it just be `ga4gh:{refgetAccession}`?

update models from 2.0-alpha changes
